### ISSUE TITLE
Cannot add milicast-flutter-sdk

### ISSUE THREAD

**Issue by aiman97adzhar** [millicast/flutter-sdk#5]
After i used command
-flutter pub add millicast-flutter-sdk

I got an error which is
-Because kandack depends on millicast-flutter-sdk any which doesn't exist (could not find package millicast-flutter-sdk at https://pub.dartlang.org), version solving failed.

![Screenshot at Apr 13 14-54-11](https://user-images.githubusercontent.com/97024467/163117839-fa96006b-8e9d-43ac-b7f0-7bdbb3a59701.png)

@goddino @Jerricho93 @ftejeria @fcancela

**Comment by fcancela** [comment]
Hello @aiman97adzhar ,

README instructions were written assumming that the library would already be published in pub.dev. As we haven't published it yet, I have added a note to the README with a way in which you can add millicast_flutter_sdk as a dependency to your project.

Inside your pubspec.yaml file of your project, add:

```yaml
dependencies:
  flutter:
    sdk: flutter
  millicast_flutter_sdk:
    git:
      url: https://github.com/millicast/flutter-sdk.git
      ref: beta-test # branch name
```

Please use beta-test branch as develop branch still has some untested features.
